name: Compile CV

on:
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-latex-base texlive-fonts-recommended texlive-fonts-extra
          mkdir pdfs

      - name: Create CV - Swedish
        run: |
          for file in personal_letter/swedish/industrier/*; do
            sed -i "s|\\subfile{personal_letter/swedish/industrier/ignore}|\\subfile{personal_letter/swedish/industrier/${file%.*}}|" swedish.tex
            file=${file##*/}; 
            file=${file%.*}; 
            pdflatex -jobname=swedish_$file swedish.tex
          done

      - name: Create CV - English
        run: |
          for file in personal_letter/english/industries/*; do
            sed -i "s|\\subfile{personal_letter/english/industries/ignore}|\\subfile{personal_letter/english/industries/$(basename "$file" .tex)}|g" "english.tex"
            pdflatex -output-directory=pdfs -jobname=english_$file "english.tex"
          done

      - name: cleanup
        run: |

      - name: Upload CV
        uses: actions/upload-artifact@v2
        with:
          name: CVs
          path: |
            ./
